name: ci-python

on: [push]
jobs: 
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: 3.10.1
      - run: python -m unittest
      - run: python very_simple.py

